Controllers/AdminController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using SmartStore.Models;
using SmartStore.Services;
using SmartStore.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartStore.Controllers
{
    [Authorize(Roles = RoleName.Admin)]
    public class AdminController : Controller
    {
        IAdminService _adminService;
        public AdminController(IAdminService adminService)
        {
            _adminService = adminService;
        }
        // admin/addstoremanager
        public ActionResult AddStoreManager()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddManager(ApplicationDbContext context, StoreManager storeManager)
        {
            if (ModelState.IsValid)
            {
                var result = _adminService.CreateStoreManager(context, storeManager);

                if (result)
                {
                    ViewBag.NewManager = "Store Manager Added succesffully";
                    return View("~/Views/Shop/StockAdmin.cshtml");
                }
                else
                {
                    ViewBag.NewManager = "User already exist";
                    return View("~/Views/Shop/StockAdmin.cshtml");
                }
            }
            else
            {
                return View("AddStoreManager", storeManager);
            }
        }
    }
}

Views/Admin/AddStoreManager.cshtml
@model SmartStore.Models.StoreManager
@{
    ViewBag.Title = "AddStoreManager";
}

<h2>AddStoreManager</h2>

@using (Html.BeginForm("AddManager", "Admin"))
{
    @Html.ValidationSummary(true, "Please fix the following issues");
    //excludepropertyErrors set to true in order to removes the list of errors and pass a default msg
    <div class="form-group">
        @Html.LabelFor(i => i.EmailAddress)
        @Html.TextBoxFor(i => i.EmailAddress, new { @class = "form-control" })
        @Html.ValidationMessageFor(i => i.EmailAddress)
    </div>
    <div class="form-group">
        @Html.LabelFor(i => i.Password)
        @Html.PasswordFor(i => i.Password, new { @class = "form-control" })
        @Html.ValidationMessageFor(i => i.Password)
    </div>
    <button type="submit" class="btn btn-success">Add New Store Manager</button>
}