Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SmartStore.Models
{
    public class Item
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required(ErrorMessage = "Item name cannot be empty")]
        [StringLength(50)]
        public string Name { get; set; }

        [Required]
        [Range(typeof(int), "1", "100000", ErrorMessage = "Quantity range is between 1-100000")]
        public int Quantity { get; set; }

        [Required]
        [Range(typeof(double), "1", "1000000000000", ErrorMessage ="Amount should be greater than 0 or less than a billion" )]
        public double Amount { get; set; }

        [Display(Name = "Expiration Date")] // what is shown on the form label
        public DateTime? ExpiringDate { get; set; }


        [Required(ErrorMessage = "choose file")]
        [Display(Name = "Upload Image")]
        public string ImagePath { get; set; }


        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }


        // Category Navigation prop
        public Category Category { get; set; }

        [Display(Name = "Category")]
        [Required(ErrorMessage = "Please select a Category")]
        public byte CategoryId { get; set; }


        // Supplier Navigation Prop
        public Supplier Supplier { get; set; }

        [Display(Name = "Supplier")]
        [Required(ErrorMessage = "Please select a Supplier")]
        public byte SupplierId { get; set; }
    }
}

Controllers/ShopController.cs
using SmartStore.Models;
using SmartStore.ViewModel;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartStore.Services;
using System.IO;

namespace SmartStore.Controllers
{
    public class ShopController : Controller
    {
        IShopService _shopService;
        public ShopController(IShopService shopService)
        {
            _shopService = shopService;
        }
        // GET: Items in stock
        public ActionResult Products()
        {
            //var searchDb = TempData["searchDb"] as List<Item>;

            List<Item> items;

            // if (searchDb == null)
            if (!(TempData["searchDb"] is List<Item> searchDb))
                items = _shopService.GetAllProducts();
            else
                items = searchDb;
            
            //If the Admin is logged in, show the admin dashboard(stockAdmin)
            if (User.IsInRole(RoleName.Admin))
                return View("StockAdmin", items);
            else
            {
                if (User.IsInRole(RoleName.StoreManager))
                    return View("StockList", items);
            }
            // no user is loged in
            return View("Products", items);
        }


        [HttpGet]
        [Authorize(Roles = RoleName.Admin + "," + RoleName.StoreManager)]
        public ActionResult AddNewItem()
        {
            var itemViewModel = _shopService.ItemViewModel();

            return View("ItemForm", itemViewModel);
        }

        // saves the item into the DB
        [HttpPost]
        [Authorize(Roles = RoleName.Admin + "," + RoleName.StoreManager)]
        public ActionResult Save(Item item)
        {
            // frontend handles validation

            if (item.Id == 0)
                _shopService.AddItemToDb(item);
            else
                _shopService.UpdateItemInDb(item);
            
 
            return RedirectToAction("Products");
        }

        [Authorize(Roles = RoleName.Admin + "," + RoleName.StoreManager)]
        public ActionResult Edit(int id)
        {
            var itemInDb = _shopService.EditItemInDb(id);

            if (itemInDb == null)
                return HttpNotFound();

            return View("ItemForm", itemInDb);
        }

        //Delete an Item
        [Authorize(Roles = RoleName.StoreManager)]
        public ActionResult Delete(int id)
        {
            var item = _shopService.DeleteItem(id);

            if (item == null)
                return HttpNotFound();

            return RedirectToAction("Products");
        }

        //Get Item details
        public ActionResult Details (int Id)
        {
            var productDetails = _shopService.GetItemDetails(Id);

            if (productDetails == null)
                return HttpNotFound();

            return View(productDetails);
        }

        //Search DB
        public ActionResult Search(string search)
        {
            if (string.IsNullOrEmpty(search))
                return RedirectToAction("Products");

            var items = _shopService.SearchDb(search);

            //return View(items);
            TempData["searchDb"] = items;

            return RedirectToAction("Products");
        }
        public ActionResult GetAllOrder()
        {
            var pendinOrders = _shopService.GetAllOrder();
            return View(pendinOrders);
        }
        public ActionResult GetOrder(string id)
        {
            var orders = _shopService.GetOrder(id);
            return View(orders);
        }
    }
}

Views/Shop/Details.cshtml
@model SmartStore.Models.Item
@{
    ViewBag.Title = "Details";
}

<h2>Product Details</h2>

<div class="panel panel-info">
    <div class="panel-heading">
        <h1 class="panel-title">@Model.Name</h1>
    </div>
    <ul class="list-group">
        <li class="list-group-item text-center">
            <img src="@Url.Content(@Model.ImagePath)" alt="..." class="img-rounded img-responsive" style="width: 450px">
        </li>
        <li class="list-group-item">Amount: $@Model.Amount</li>
        <li class="list-group-item">Expiry Date: @string.Format("{0:d MMM, yyyy}", @Model.ExpiringDate) </li>
        <li class="list-group-item">Category: @Model.Category.Name</li>
        <li class="list-group-item">Description: Lorem Ipsum sit dolor amiet... </li>
    </ul>
</div>

Views/Shop/GetAllOrder.cshtml
@model List<string>
@{
    ViewBag.Title = "Items";
}

<h2>All orders</h2>
<div>

    <div class="panel panel-success">
        <div class="panel-heading" style="height: 50px">
            <div class="col-md-6">
                <h1 class="panel-title">Items in Stock</h1>
            </div>
        </div>
        <div class="panel-body">
            @if (!Model.Any())
            {
                <p>No Order</p>
            }
            else
            {
        <table id="items" class="table table-hover">
            <tr class="info">
                <th>User ID</th>
                <th>Order</th>
            </tr>
            @foreach (var userId in Model)
            {
                <tr class="info">
                    <td>@Html.ActionLink(@userId, "GetOrder", "Shop", new { id = userId }, null) </td>
                    <td>
                        @Html.ActionLink("Get Order", "GetOrder", "Shop", new { id = userId },
                                         new { @class = "btn btn-primary" })
                    </td>
                </tr>
                
            }
        </table>
            }
        </div>
    </div>

</div>

Views/Shop/GetOrder.cshtml
@model IEnumerable<SmartStore.Models.UserCart>

@{
    ViewBag.Title = "GetOrder";
    var userName = "uu";
}
<h2>GetOrder</h2>
<div>

    <div class="panel panel-success">
        <div class="panel-heading" style="height: 50px">
            <div class="col-md-6">
                <h1 class="panel-title">User Name: userName</h1>
            </div>
        </div>
        <div class="panel-body">
            @if (!Model.Any())
            {
                <p>No items in stock</p>
            }
            else
            {
                <table id="items" class="table table-hover">
                    <tr class="info">
                        <th>Name</th>
                        <th>Amount</th>
                        <th>Quantity</th>
                        <th>Processing</th>
                        <th></th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr class="info">
                            <td>@item.ItemName</td>
                            <td>@item.Amount</td>
                            <td>@item.Quantity</td>
                            <td>@item.Processing</td>
                            <td>
                                @Html.ActionLink("Process", "", "Shop", new { id = item.Id },
                                 new { @class = "btn btn-success" })

                            </td>
                        </tr>
                    }
                </table>
            }
        </div>
    </div>

</div>

Views/Shop/ItemForm.cshtml
@model SmartStore.ViewModel.ItemViewModel
@{
    ViewBag.Title = "AddNewItem";
}

<h2>AddNewItem</h2>

@using (Html.BeginForm("Save", "Shop", FormMethod.Post, new {enctype = "Multipart/Form-Data" }))
{
    @Html.ValidationSummary(true, "Please fix the following issues");
    //excludepropertyErrors set to true in order to removes the list of errors and pass a default msg
    <div class="form-group">
        @Html.LabelFor(i => i.Item.Name)
        @Html.TextBoxFor(i => i.Item.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(i => i.Item.Name)
    </div>
    <div class="form-group">
        @Html.LabelFor(i => i.Item.Amount)
        @Html.TextBoxFor(i => i.Item.Amount, new { @class = "form-control" })
        @Html.ValidationMessageFor(i => i.Item.Amount)

    </div>
    <div class="form-group">
        @Html.LabelFor(i => i.Item.ExpiringDate)
        @Html.TextBoxFor(i => i.Item.ExpiringDate, "{0:d MMM yyyy}", new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(i => i.Item.Quantity)
        @Html.TextBoxFor(i => i.Item.Quantity, new { @class = "form-control" })
        @Html.ValidationMessageFor(i => i.Item.Quantity)

    </div>
    <div class="form-group">
        @Html.LabelFor(i => i.Item.SupplierId)
        @Html.DropDownListFor(i => i.Item.SupplierId, new SelectList(Model.Supplier, "Id", "Name"), "Select Supplier", new { @class = "form-control" })
        @Html.ValidationMessageFor(i => i.Item.SupplierId)

    </div>
    <div class="form-group">
        @Html.LabelFor(i => i.Item.CategoryId)
        @Html.DropDownListFor(i => i.Item.CategoryId, new SelectList(Model.Categories, "Id", "Name"), "Select Category", new { @class = "form-control" })
        @Html.ValidationMessageFor(i => i.Item.CategoryId)

    </div>
    <div class="form-group">
        @Html.LabelFor(i => i.Item.ImagePath)
        <input type="file" name=@Html.NameFor(i =>i.Item.ImageFile) required/>
        @*<input type="file" id="ImageFile" name="ImageFile" required/>*@
        @Html.ValidationMessageFor(i => i.Item.ImagePath)
    </div>
    @Html.HiddenFor(i => i.Item.Id)

    <button type="submit" class="btn btn-success">Save</button>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval");
}

Views/Shop/Products.cshtml
@model IEnumerable<SmartStore.Models.Item>
@{
    ViewBag.Title = "Items";
}

<h2>Shop Smartly</h2>
@*store manager cannot add or delete item*@


<div>
    <div class="panel panel-success">
        <div class="panel-heading" style="height: 50px">
            <div class="col-xs-11 col-sm-11 col-md-11 col-lg-11">
                @Html.Partial("_SearchTab", new { @class = "panel-title" })
            </div>
            <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
                @Html.ActionLink(" ", "Index", "Cart", null, new { @class = "glyphicon glyphicon-shopping-cart" })
            </div>
        </div>
        <div class="panel-body">
            @if (!Model.Any())
            {
                <p>No items in stock</p>
            }
            else
            {   foreach (var item in Model)
                 {
                    <div class="panel panel-default col-xs-6 col-sm-12 col-sm-6 col-md-3 col-lg-3">
                        <div class="panel-heading">
                            @*@Html.DisplayFor(item.ImagePath)*@
                            <img src="@Url.Content(item.ImagePath)" alt="..." class="img-rounded img-responsive text-center" style="height: 200px">
                            @*<img src="~/Content/Images/Screenshot (14).png" class="img-responsive"/>*@
                            @*add the name here with the    image*@
                        </div>
                        <div class="panel-body">
                            <h3 class="text-center"> <strong>@item.Name</strong> </h3>
                            <i>$@item.Amount</i>
                            <p>@item.Category.Name</p>
                            @Html.ActionLink("Details", "Details", "Shop", new { id = item.Id },
                                    new { @class = "btn btn-success" })

                            @Html.ActionLink("Add to cart", "AddToCart", "Cart", new { id = item.Id },
                                    new { @class = "btn btn-warning" })
                        </div>
                    </div>


                        @*<tr class="info">
                            <td>@item.Name</td>
                            <td>$@item.Amount</td>
                            <td>@item.Category.Name </td>
                            <td>
                                @Html.ActionLink("Details", "Details", "Shop", new { id = item.Id },
                                    new { @class = "btn btn-info" })
                            </td>
                            <td>
                                @Html.ActionLink("Add to cart", "AddToCart", "Cart", new { id = item.Id },
                                    new { @class = "btn btn-success add-btn" })
                            </td>
                        </tr>*@
                    }
            }
        </div>
    </div>

</div>
@section scripts
{
    <script>
        $(document).ready(function () {

            $("#items").on("click", ".add-btn", function () {

                alert("Item Added");
            })
        });
    </script>
}

Views/Shop/Search.cshtml
@model IEnumerable<SmartStore.Models.Item>
@{
    ViewBag.Title = "Items";
}

<h2>Search</h2>
@*store manager cannot add or delete item*@

<div>
    <div class="panel panel-success">
        <div class="panel-heading">
            <h1 class="panel-title">Items in Stock</h1>
        </div>
        <div class="panel-body">
            @if (!Model.Any())
            {
                <p>No items in stock</p>
            }
            else
            {
                <table id="items" class="table table-hover">
                    <tr class="info">
                        <th>Name</th>
                        <th>Amount</th>
                        <th>Category</th>
                        <th></th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr class="info">
                            <td>@item.Name</td>
                            @*add message on hover*@
                            <td>$@item.Amount</td>
                            <td>@item.Category.Name </td>
                            <td>
                                @Html.ActionLink("Details", "Details", "Shop", new { id = item.Id },
                                    new { @class = "btn btn-info" })
                            </td>
                            <td>
                                @Html.ActionLink("Add to cart", "AddToCart", "Cart", new { id = item.Id },
                                    new { @class = "btn btn-success" })
                            </td>
                        </tr>
                    }
                </table>
            }
        </div>
    </div>

</div>
@section scripts
{
    @*client side validification*@
    @Scripts.Render("~/Scripts/jquery.validate")



}

Views/Shop/StockAdmin.cshtml
@model IEnumerable<SmartStore.Models.Item>
@{
    ViewBag.Title = "Items";
}
    
<h2>Admin Dashboard</h2>
@if(ViewBag.NewManager != null)
{
<p>@ViewBag.NewManager</p>
}

<div>
    @Html.ActionLink("Add New Item", "AddNewItem", "Shop", new { @class = "btn btn-primary" })
    @Html.ActionLink("Add New Store Manager", "AddStoreManager", "admin", null, new { @class = "btn btn-primary" })


    <div class="panel panel-success">
        <div class="panel-heading">
            <h1 class="panel-title">Items in Stock</h1>
        </div>
        
    </div>
</div>
@section scripts
{
    @*client side validification*@
    @Scripts.Render("~/Scripts/jquery.validate")
    
}

Views/Shop/StockList.cshtml
@model IEnumerable<SmartStore.Models.Item>
@{
    ViewBag.Title = "Items";
}

<h2>Store Manager Dashboard</h2>
<div>
    @Html.ActionLink("Add New Item", "AddNewItem", "Shop", new { @class = "btn btn-primary" })

    <div class="panel panel-success">
        <div class="panel-heading" style="height: 50px">
            <div class="col-md-6">
                <h1 class="panel-title">Items in Stock</h1>
            </div>
            <div class="col-md-6">
                @Html.Partial("_SearchTab", new { @class = "panel-title" })
            </div>
        </div>
        <div class="panel-body">
            @if (!Model.Any())
            {
                <p>No items in stock</p>
            }
            else
            {
                <table id="items" class="table table-hover">
                    <tr class="info">
                        <th>Name</th>
                        <th>Amount</th>
                        <th>Quantity</th>
                        <th>Category</th>
                        <th>Supplier</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr class="info">
                            <td>@Html.ActionLink(@item.Name, "Edit", "Shop", new { id = item.Id }, null)</td>
                            @*add message on hover*@
                            <td>$@item.Amount</td>
                            <td>@item.Quantity</td>
                            <td>@item.Category.Name </td>
                            <td>@item.Supplier.Name </td>
                            @*<td>@string.Format("{0:d MMM, yyyy}", @item.ExpiringDate)</td>*@
                            <td>
                                @Html.ActionLink("Edit", "Edit", "Shop", new { id = item.Id },
                                 new { @class = "btn btn-info" })

                            </td>
                            <td>
                                @Html.ActionLink("Details", "Details", "Shop", new { id = item.Id },
                                     new { @class = "btn btn-success" })
                            </td>
                            <td>
                                @Html.ActionLink("Delete", "Delete", "Shop", new { id = item.Id },
                               new { @class = "btn btn-danger" })
                                @*<button data-item-id="@item.Id" class="btn btn-danger delete-btn">Delete</button>*@
                            </td>
                        </tr>
                    }
                </table>
            }
        </div>
    </div>
    
</div>
@section scripts
{
    @*client side validification*@
    @Scripts.Render("~/Scripts/jquery.validate")
    @Scripts.Render("~/bundles/lib") 

    <script>
        $(document).ready(function () {

            $("#items").on("click", ".delete-btn", function () {

                var deleteButton = $(this); //the clicked button

                if (confirm("Are you sure you want to delete this item ?"))
                    $.ajax({
                        url: "/Shop/Delete/" + deleteButton.attr("data-item-id"), // calls the delete method and passes the id
                        success: function () { // removing the table role from the view
                            //console.log("Deleted successfully");
                            deleteButton.parents("tr").remove();
                        }
                    })
            })
        });
    </script>

}